import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { ConfigSchema } from "../src/config.ts";
import { inventory } from "../src/inventory/run.ts";
import { Ledger } from "../src/ledger/db.ts";

const FIXTURE = resolve(import.meta.dirname, "../fixtures/mini-app");

describe("inventory on fixtures/mini-app", () => {
	it("accounts for every file, finds dead code, tiers leaves first", async () => {
		const ledger = new Ledger(":memory:");
		const config = ConfigSchema.parse({ source: { path: FIXTURE, stack: "php" }, target: { path: "/tmp/x", stacks: ["nestjs"] }, models: {} });
		const r = await inventory(config, FIXTURE, ledger);

		expect(r.invariantsOk).toBe(true);
		expect(r.dead).toEqual(["legacy/old_export.php"]);
		expect(r.largestScc).toBe(1);
		// every live symbol is clustered, every dead one dropped → nothing stuck in 'discovered'
		expect(ledger.status().symbols["discovered"] ?? 0).toBe(0);

		const units = ledger.listUnits();
		const byFile = Object.fromEntries(units.map((u) => [JSON.parse(u.meta).files[0], u]));
		expect(byFile["src/Config.php"].tier).toBe("T0");
		expect(byFile["src/Money.php"].tier).toBe("T0");
		expect(byFile["src/Pricing.php"].tier).toBe("T1");
		expect(byFile["src/InvoiceRepo.php"].tier).toBe("T1");
		expect(byFile["src/InvoiceRepo.php"].kind).toBe("data_access");
		expect(byFile["templates/invoice.php"].tier).toBe("T2");
		expect(byFile["templates/invoice.php"].kind).toBe("template");
		expect(byFile["src/controllers/InvoiceController.php"].tier).toBe("T2");
		expect(byFile["routes.php"]).toBeUndefined(); // registration file: regenerated by the target adapter, not a unit
		expect(ledger.fileState("routes.php")).toBe("regenerated");
		expect(r.regenerated).toEqual(["routes.php"]);

		// leaves first: unit ids are numbered in topological order, so every dep has a smaller id
		const pos = new Map([...units].sort((a, b) => a.id.localeCompare(b.id)).map((u, i) => [u.id, i]));
		for (const u of units) for (const d of JSON.parse(u.deps) as string[]) expect(pos.get(d)!).toBeLessThan(pos.get(u.id)!);

		// routes resolved to handler symbols; SQL tables extracted
		const routes = ledger.db.prepare("SELECT handler_symbol FROM index_routes").all() as Array<{ handler_symbol: string }>;
		expect(routes.map((x) => x.handler_symbol).sort()).toEqual([
			"src/controllers/InvoiceController.php::InvoiceController::create",
			"src/controllers/InvoiceController.php::InvoiceController::recent",
			"src/controllers/InvoiceController.php::InvoiceController::show",
		]);
		const tables = (ledger.db.prepare("SELECT tables FROM index_queries").all() as Array<{ tables: string }>).flatMap((x) => JSON.parse(x.tables));
		expect(new Set(tables)).toEqual(new Set(["invoices"]));
	});
});
